#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CatalystFacadeDemo.Droid.Resource", IsApplication=true)]

namespace AltGeoRelayService.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CatalystFacade.Droid.Resource.String.ApplicationName = global::CatalystFacadeDemo.Droid.Resource.String.ApplicationName;
			global::CatalystFacade.Droid.Resource.String.app_name = global::CatalystFacadeDemo.Droid.Resource.String.app_name;
			global::CatalystFacade.Droid.Resource.String.com_trimble_empower_modulemanager_app_name = global::CatalystFacadeDemo.Droid.Resource.String.com_trimble_empower_modulemanager_app_name;
			global::CatalystFacade.Droid.Resource.String.Hello = global::CatalystFacadeDemo.Droid.Resource.String.Hello;
			global::CatalystFacade.Droid.Resource.String.hello = global::CatalystFacadeDemo.Droid.Resource.String.hello;
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::CatalystFacadeDemo.Droid.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.font = global::CatalystFacadeDemo.Droid.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::CatalystFacadeDemo.Droid.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::CatalystFacadeDemo.Droid.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.androidx_core_ripple_material_light = global::CatalystFacadeDemo.Droid.Resource.Color.androidx_core_ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.androidx_core_secondary_text_default_material_light = global::CatalystFacadeDemo.Droid.Resource.Color.androidx_core_secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::CatalystFacadeDemo.Droid.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::CatalystFacadeDemo.Droid.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::CatalystFacadeDemo.Droid.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::CatalystFacadeDemo.Droid.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::CatalystFacadeDemo.Droid.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::CatalystFacadeDemo.Droid.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::CatalystFacadeDemo.Droid.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::CatalystFacadeDemo.Droid.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::CatalystFacadeDemo.Droid.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::CatalystFacadeDemo.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::CatalystFacadeDemo.Droid.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::CatalystFacadeDemo.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.accessibility_action_clickable_span = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_action_clickable_span;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_0 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_0;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_1 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_1;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_10 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_10;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_11 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_11;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_12 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_12;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_13 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_13;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_14 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_14;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_15 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_15;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_16 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_16;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_17 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_17;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_18 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_18;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_19 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_19;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_2 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_2;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_20 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_20;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_21 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_21;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_22 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_22;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_23 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_23;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_24 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_24;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_25 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_25;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_26 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_26;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_27 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_27;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_28 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_28;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_29 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_29;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_3 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_3;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_30 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_30;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_31 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_31;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_4 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_4;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_5 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_5;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_6 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_6;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_7 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_7;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_8 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_8;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_9 = global::CatalystFacadeDemo.Droid.Resource.Id.accessibility_custom_action_9;
			global::Xamarin.Essentials.Resource.Id.actions = global::CatalystFacadeDemo.Droid.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::CatalystFacadeDemo.Droid.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::CatalystFacadeDemo.Droid.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::CatalystFacadeDemo.Droid.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::CatalystFacadeDemo.Droid.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.async = global::CatalystFacadeDemo.Droid.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::CatalystFacadeDemo.Droid.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::CatalystFacadeDemo.Droid.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::CatalystFacadeDemo.Droid.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::CatalystFacadeDemo.Droid.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::CatalystFacadeDemo.Droid.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::CatalystFacadeDemo.Droid.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::CatalystFacadeDemo.Droid.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.dialog_button = global::CatalystFacadeDemo.Droid.Resource.Id.dialog_button;
			global::Xamarin.Essentials.Resource.Id.forever = global::CatalystFacadeDemo.Droid.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::CatalystFacadeDemo.Droid.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::CatalystFacadeDemo.Droid.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::CatalystFacadeDemo.Droid.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::CatalystFacadeDemo.Droid.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::CatalystFacadeDemo.Droid.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::CatalystFacadeDemo.Droid.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::CatalystFacadeDemo.Droid.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::CatalystFacadeDemo.Droid.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::CatalystFacadeDemo.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::CatalystFacadeDemo.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::CatalystFacadeDemo.Droid.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::CatalystFacadeDemo.Droid.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_actions = global::CatalystFacadeDemo.Droid.Resource.Id.tag_accessibility_actions;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_clickable_spans = global::CatalystFacadeDemo.Droid.Resource.Id.tag_accessibility_clickable_spans;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_heading = global::CatalystFacadeDemo.Droid.Resource.Id.tag_accessibility_heading;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_pane_title = global::CatalystFacadeDemo.Droid.Resource.Id.tag_accessibility_pane_title;
			global::Xamarin.Essentials.Resource.Id.tag_screen_reader_focusable = global::CatalystFacadeDemo.Droid.Resource.Id.tag_screen_reader_focusable;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::CatalystFacadeDemo.Droid.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::CatalystFacadeDemo.Droid.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::CatalystFacadeDemo.Droid.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::CatalystFacadeDemo.Droid.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::CatalystFacadeDemo.Droid.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::CatalystFacadeDemo.Droid.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::CatalystFacadeDemo.Droid.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.view_tree_lifecycle_owner = global::CatalystFacadeDemo.Droid.Resource.Id.view_tree_lifecycle_owner;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::CatalystFacadeDemo.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::CatalystFacadeDemo.Droid.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::CatalystFacadeDemo.Droid.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.custom_dialog = global::CatalystFacadeDemo.Droid.Resource.Layout.custom_dialog;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::CatalystFacadeDemo.Droid.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::CatalystFacadeDemo.Droid.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::CatalystFacadeDemo.Droid.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::CatalystFacadeDemo.Droid.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::CatalystFacadeDemo.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::CatalystFacadeDemo.Droid.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.copy_toast_msg = global::CatalystFacadeDemo.Droid.Resource.String.copy_toast_msg;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_copy_link = global::CatalystFacadeDemo.Droid.Resource.String.fallback_menu_item_copy_link;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_open_in_browser = global::CatalystFacadeDemo.Droid.Resource.String.fallback_menu_item_open_in_browser;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_share_link = global::CatalystFacadeDemo.Droid.Resource.String.fallback_menu_item_share_link;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::CatalystFacadeDemo.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::CatalystFacadeDemo.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::CatalystFacadeDemo.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::CatalystFacadeDemo.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::CatalystFacadeDemo.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::CatalystFacadeDemo.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::CatalystFacadeDemo.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::CatalystFacadeDemo.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::CatalystFacadeDemo.Droid.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::CatalystFacadeDemo.Droid.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::CatalystFacadeDemo.Droid.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::CatalystFacadeDemo.Droid.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::CatalystFacadeDemo.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColorItem_android_offset;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::CatalystFacadeDemo.Droid.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Xml.image_share_filepaths = global::CatalystFacadeDemo.Droid.Resource.Xml.image_share_filepaths;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::CatalystFacadeDemo.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fragment_fast_out_extra_slow_in = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int fragment_close_enter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fragment_close_exit = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fragment_fade_enter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fragment_fade_exit = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fragment_open_enter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fragment_open_exit = 2130837509;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int activityAction = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int activityName = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int alpha = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int alwaysExpand = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int animationBackgroundColor = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int clearTop = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int coordinatorLayoutStyle = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int drawerLayoutStyle = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int elevation = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int finishPrimaryWithPlaceholder = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int finishPrimaryWithSecondary = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int finishSecondaryWithPrimary = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int font = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int fontProviderAuthority = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int fontProviderCerts = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int fontProviderFetchStrategy = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int fontProviderFetchTimeout = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int fontProviderPackage = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int fontProviderQuery = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int fontProviderSystemFontFamily = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int fontStyle = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int fontVariationSettings = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int fontWeight = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int keylines = 2130903063;
			
			// aapt resource value: 0x7F030019
			public const int layout_anchor = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int layout_anchorGravity = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int layout_behavior = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int layout_dodgeInsetEdges = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int layout_insetEdge = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int layout_keyline = 2130903070;
			
			// aapt resource value: 0x7F030018
			public const int lStar = 2130903064;
			
			// aapt resource value: 0x7F03001F
			public const int nestedScrollViewStyle = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int placeholderActivityName = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int primaryActivityName = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int queryPatterns = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int secondaryActivityAction = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int secondaryActivityName = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int shortcutMatchRequired = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int splitLayoutDirection = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int splitMaxAspectRatioInLandscape = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int splitMaxAspectRatioInPortrait = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int splitMinHeightDp = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int splitMinSmallestWidthDp = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int splitMinWidthDp = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int splitRatio = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int statusBarBackground = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int stickyPlaceholder = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int swipeRefreshLayoutProgressSpinnerBackgroundColor = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int tag = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int ttcIndex = 2130903089;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int androidx_core_ripple_material_light = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int androidx_core_secondary_text_default_material_light = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int browser_actions_bg_grey = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int browser_actions_divider_color = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int browser_actions_text_color = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int browser_actions_title_color = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int call_notification_answer_color = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int call_notification_decline_color = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_action_color_filter = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_icon_bg_color = 2130968585;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int browser_actions_context_menu_max_width = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int browser_actions_context_menu_min_padding = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int compat_button_inset_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int compat_button_inset_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int compat_button_padding_horizontal_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int compat_button_padding_vertical_material = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int compat_control_corner_material = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int compat_notification_large_icon_max_height = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int compat_notification_large_icon_max_width = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int def_drawer_elevation = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_action_icon_size = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_action_text_size = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_big_circle_margin = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_content_margin_start = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notification_large_icon_height = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int notification_large_icon_width = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int notification_main_column_padding_top = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notification_media_narrow_margin = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int notification_right_icon_size = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_right_side_padding_top = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int notification_small_icon_background_padding = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int notification_small_icon_size_as_large = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int notification_subtext_size = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int notification_top_pad = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int notification_top_pad_large_text = 2131034136;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int abc_vector_test = 2131099648;
			
			// aapt resource value: 0x7F06000B
			public const int Icon = 2131099659;
			
			// aapt resource value: 0x7F060001
			public const int ic_call_answer = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_call_answer_low = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int ic_call_answer_video = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ic_call_answer_video_low = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int ic_call_decline = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int ic_call_decline_low = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int ic_clear = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int ic_delete = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int ic_save = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int ic_settings = 2131099658;
			
			// aapt resource value: 0x7F06000C
			public const int notification_action_background = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int notification_bg = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int notification_bg_low = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int notification_bg_low_normal = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int notification_bg_low_pressed = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int notification_bg_normal = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int notification_bg_normal_pressed = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int notification_icon_background = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int notification_oversize_large_icon_bg = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int notification_template_icon_bg = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int notification_template_icon_low_bg = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int notification_tile_bg = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int notify_panel_notification_icon_bg = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int RoundedRectGreen = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int RoundedRectGrey = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int RoundedRectRed = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int trimble = 2131099676;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070005
			public const int accessibility_action_clickable_span = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int accessibility_custom_action_0 = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int accessibility_custom_action_1 = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int accessibility_custom_action_10 = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int accessibility_custom_action_11 = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int accessibility_custom_action_12 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int accessibility_custom_action_13 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int accessibility_custom_action_14 = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int accessibility_custom_action_15 = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int accessibility_custom_action_16 = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int accessibility_custom_action_17 = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int accessibility_custom_action_18 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int accessibility_custom_action_19 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int accessibility_custom_action_2 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int accessibility_custom_action_20 = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int accessibility_custom_action_21 = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int accessibility_custom_action_22 = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int accessibility_custom_action_23 = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int accessibility_custom_action_24 = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int accessibility_custom_action_25 = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int accessibility_custom_action_26 = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int accessibility_custom_action_27 = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int accessibility_custom_action_28 = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int accessibility_custom_action_29 = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int accessibility_custom_action_3 = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int accessibility_custom_action_30 = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int accessibility_custom_action_31 = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int accessibility_custom_action_4 = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int accessibility_custom_action_5 = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int accessibility_custom_action_6 = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int accessibility_custom_action_7 = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int accessibility_custom_action_8 = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int accessibility_custom_action_9 = 2131165221;
			
			// aapt resource value: 0x7F07002A
			public const int actions = 2131165226;
			
			// aapt resource value: 0x7F070026
			public const int action_container = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int action_divider = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int action_image = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int action_text = 2131165225;
			
			// aapt resource value: 0x7F07002B
			public const int adjacent = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int all = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int always = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int alwaysAllow = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int alwaysDisallow = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int androidx_window_activity_scope = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int async = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int blocking = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int bottom = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int bottomToTop = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int browser_actions_header_text = 2131165237;
			
			// aapt resource value: 0x7F070038
			public const int browser_actions_menu_items = 2131165240;
			
			// aapt resource value: 0x7F070036
			public const int browser_actions_menu_item_icon = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int browser_actions_menu_item_text = 2131165239;
			
			// aapt resource value: 0x7F070039
			public const int browser_actions_menu_view = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int btnBthSearch = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int btnChangeCorrectionSourceSettings = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int btnCheckOnDemand = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int btnClearMarking = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int btnConnect = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int btnDisconnect = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int btnEndSurvey = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int btnExportLogs = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int btnGeoidFileChoose = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int btnGetNtripSourceList = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int btnInstallRTXSubscription = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int btnLoadSubscription = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int btnMailLog = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int btnMarkPoints = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int btnOpenFacadeLog = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int btnStartSurvey = 2131165257;
			
			// aapt resource value: 0x7F070000
			public const int ButtonBTPaired = 2131165184;
			
			// aapt resource value: 0x7F07004A
			public const int center = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int center_horizontal = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int center_vertical = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int chronometer = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int clip_horizontal = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int clip_vertical = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int dialog_button = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int edit_text_id = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int edtDeviceAddress = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int edtDevicePort = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int edtGeoidGridFileFullPath = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int edtInstallRTXSubscription = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int edtNtripPassword = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int edtNtripPort = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int edtNtripServer = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int edtNtripUserName = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int edtReducedAntennaHght = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int edtTargetReferenceFrameId = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int end = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int fill = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int fill_horizontal = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int fill_vertical = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int forever = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int fragment_container_view_tag = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int ghost_view = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int ghost_view_holder = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int hide_ime_id = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int icon = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int icon_group = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int info = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int italic = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int layoutAddress = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int layoutConnectionType = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int layoutDevicePort = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int layoutInstallCodes = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int layoutLicStatus = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int layoutMailLog = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int layoutSensorStatus = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int layoutSurveyStatus = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int lblRtkConnectionStatus = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int lblRtkSurveyType = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int left = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int line1 = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int line3 = 2131165301;
			
			// aapt resource value: 0x7F070001
			public const int ListViewBTSelect = 2131165185;
			
			// aapt resource value: 0x7F070076
			public const int locale = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int lstPosition = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int lstSatellites = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int ltr = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int menuClear = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int menuConfiguration = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int menuSave = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int never = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int none = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int normal = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int notification_background = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int notification_main_column = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int notification_main_column_container = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int parent_matrix = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int report_drawn = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int right = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int right_icon = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int right_side = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int rtl = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int save_non_transition_alpha = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int save_overlay_view = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int special_effects_controller_view_tag = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int spnrConnType = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int spnrDriverType = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int spnrNtripSource = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int spnrSubscriptionType = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int spnrSurveyType = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int spnrTargetReferenceFrame = 2131165329;
			
			// aapt resource value: 0x7F070092
			public const int start = 2131165330;
			
			// aapt resource value: 0x7F070093
			public const int switchEnableLogs = 2131165331;
			
			// aapt resource value: 0x7F070094
			public const int switchGoStatic = 2131165332;
			
			// aapt resource value: 0x7F070095
			public const int tag_accessibility_actions = 2131165333;
			
			// aapt resource value: 0x7F070096
			public const int tag_accessibility_clickable_spans = 2131165334;
			
			// aapt resource value: 0x7F070097
			public const int tag_accessibility_heading = 2131165335;
			
			// aapt resource value: 0x7F070098
			public const int tag_accessibility_pane_title = 2131165336;
			
			// aapt resource value: 0x7F070099
			public const int tag_on_apply_window_listener = 2131165337;
			
			// aapt resource value: 0x7F07009A
			public const int tag_on_receive_content_listener = 2131165338;
			
			// aapt resource value: 0x7F07009B
			public const int tag_on_receive_content_mime_types = 2131165339;
			
			// aapt resource value: 0x7F07009C
			public const int tag_screen_reader_focusable = 2131165340;
			
			// aapt resource value: 0x7F07009D
			public const int tag_state_description = 2131165341;
			
			// aapt resource value: 0x7F07009E
			public const int tag_transition_group = 2131165342;
			
			// aapt resource value: 0x7F07009F
			public const int tag_unhandled_key_event_manager = 2131165343;
			
			// aapt resource value: 0x7F0700A0
			public const int tag_unhandled_key_listeners = 2131165344;
			
			// aapt resource value: 0x7F0700A1
			public const int tag_window_insets_animation_callback = 2131165345;
			
			// aapt resource value: 0x7F0700A2
			public const int text = 2131165346;
			
			// aapt resource value: 0x7F0700A3
			public const int text2 = 2131165347;
			
			// aapt resource value: 0x7F070002
			public const int TextViewBTSelect = 2131165186;
			
			// aapt resource value: 0x7F0700A4
			public const int time = 2131165348;
			
			// aapt resource value: 0x7F0700A5
			public const int title = 2131165349;
			
			// aapt resource value: 0x7F070003
			public const int ToggleButtonBTSelect = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int Toolbar = 2131165188;
			
			// aapt resource value: 0x7F0700A6
			public const int top = 2131165350;
			
			// aapt resource value: 0x7F0700A7
			public const int topToBottom = 2131165351;
			
			// aapt resource value: 0x7F0700A8
			public const int transition_current_scene = 2131165352;
			
			// aapt resource value: 0x7F0700A9
			public const int transition_layout_save = 2131165353;
			
			// aapt resource value: 0x7F0700AA
			public const int transition_position = 2131165354;
			
			// aapt resource value: 0x7F0700AB
			public const int transition_scene_layoutid_cache = 2131165355;
			
			// aapt resource value: 0x7F0700AC
			public const int transition_transform = 2131165356;
			
			// aapt resource value: 0x7F0700AD
			public const int txtAntenna = 2131165357;
			
			// aapt resource value: 0x7F0700AE
			public const int txtBeidouSummary = 2131165358;
			
			// aapt resource value: 0x7F0700AF
			public const int txtConnectionType = 2131165359;
			
			// aapt resource value: 0x7F0700B0
			public const int txtCorrectionAge = 2131165360;
			
			// aapt resource value: 0x7F0700B1
			public const int txtCorrectionSource = 2131165361;
			
			// aapt resource value: 0x7F0700B2
			public const int txtDeviceAddress = 2131165362;
			
			// aapt resource value: 0x7F0700B3
			public const int txtDeviceConfig = 2131165363;
			
			// aapt resource value: 0x7F0700B4
			public const int txtDeviceSerialNumber = 2131165364;
			
			// aapt resource value: 0x7F0700B5
			public const int txtDriverType = 2131165365;
			
			// aapt resource value: 0x7F0700B6
			public const int txtElevation = 2131165366;
			
			// aapt resource value: 0x7F0700B7
			public const int txtExternalReceiverBatteryLevel = 2131165367;
			
			// aapt resource value: 0x7F0700B8
			public const int txtExternalReceiverBatteryLevelValue = 2131165368;
			
			// aapt resource value: 0x7F0700BA
			public const int txtGalileoSummary = 2131165370;
			
			// aapt resource value: 0x7F0700BB
			public const int txtGeoid = 2131165371;
			
			// aapt resource value: 0x7F0700BC
			public const int txtGeoidFilePath = 2131165372;
			
			// aapt resource value: 0x7F0700BD
			public const int txtGeoidModel = 2131165373;
			
			// aapt resource value: 0x7F0700BE
			public const int txtGlonassSummary = 2131165374;
			
			// aapt resource value: 0x7F0700BF
			public const int txtGoStatic = 2131165375;
			
			// aapt resource value: 0x7F0700C0
			public const int txtGpsSummary = 2131165376;
			
			// aapt resource value: 0x7F0700B9
			public const int txtGPSTime = 2131165369;
			
			// aapt resource value: 0x7F0700C1
			public const int txtGroundPositionType = 2131165377;
			
			// aapt resource value: 0x7F0700C3
			public const int txtHeight = 2131165379;
			
			// aapt resource value: 0x7F0700C2
			public const int txtHPrecision = 2131165378;
			
			// aapt resource value: 0x7F0700C4
			public const int txtIMUState = 2131165380;
			
			// aapt resource value: 0x7F0700C5
			public const int txtInstallRTXSubscription = 2131165381;
			
			// aapt resource value: 0x7F0700C6
			public const int txtIrnssSummary = 2131165382;
			
			// aapt resource value: 0x7F0700C7
			public const int txtIsTransformed = 2131165383;
			
			// aapt resource value: 0x7F0700C8
			public const int txtLatitude = 2131165384;
			
			// aapt resource value: 0x7F0700C9
			public const int txtLicStatus = 2131165385;
			
			// aapt resource value: 0x7F0700CA
			public const int txtLongitude = 2131165386;
			
			// aapt resource value: 0x7F0700CB
			public const int txtMarker = 2131165387;
			
			// aapt resource value: 0x7F0700CC
			public const int txtNoOfSatellites = 2131165388;
			
			// aapt resource value: 0x7F0700CD
			public const int txtNtrip = 2131165389;
			
			// aapt resource value: 0x7F0700CE
			public const int txtNtripPassword = 2131165390;
			
			// aapt resource value: 0x7F0700CF
			public const int txtNtripPort = 2131165391;
			
			// aapt resource value: 0x7F0700D0
			public const int txtNtripServer = 2131165392;
			
			// aapt resource value: 0x7F0700D1
			public const int txtNtripSource = 2131165393;
			
			// aapt resource value: 0x7F0700D2
			public const int txtNtripUserName = 2131165394;
			
			// aapt resource value: 0x7F0700D3
			public const int txtOutputEpoch = 2131165395;
			
			// aapt resource value: 0x7F0700D4
			public const int txtOutputReferenceFrame = 2131165396;
			
			// aapt resource value: 0x7F0700D5
			public const int txtPitch = 2131165397;
			
			// aapt resource value: 0x7F0700D6
			public const int txtPitchPrecision = 2131165398;
			
			// aapt resource value: 0x7F0700D7
			public const int txtPortNo = 2131165399;
			
			// aapt resource value: 0x7F0700D8
			public const int txtPosition = 2131165400;
			
			// aapt resource value: 0x7F0700D9
			public const int txtQzssSummary = 2131165401;
			
			// aapt resource value: 0x7F0700DA
			public const int txtReceivedCorrectionData = 2131165402;
			
			// aapt resource value: 0x7F0700DB
			public const int txtReducedAntennaHght = 2131165403;
			
			// aapt resource value: 0x7F0700DC
			public const int txtRoll = 2131165404;
			
			// aapt resource value: 0x7F0700DD
			public const int txtRollPrecision = 2131165405;
			
			// aapt resource value: 0x7F0700DE
			public const int txtRtkConnectionStatusValue = 2131165406;
			
			// aapt resource value: 0x7F0700DF
			public const int txtRtkSurveyTypeValue = 2131165407;
			
			// aapt resource value: 0x7F0700E0
			public const int txtSbasSummary = 2131165408;
			
			// aapt resource value: 0x7F0700E1
			public const int txtSensor = 2131165409;
			
			// aapt resource value: 0x7F0700E2
			public const int txtSensorStatus = 2131165410;
			
			// aapt resource value: 0x7F0700E3
			public const int txtSigmaOrientation = 2131165411;
			
			// aapt resource value: 0x7F0700E4
			public const int txtSigmaSemiMajorAxis = 2131165412;
			
			// aapt resource value: 0x7F0700E5
			public const int txtSigmaSemiMinorAxis = 2131165413;
			
			// aapt resource value: 0x7F0700E6
			public const int txtSolutionType = 2131165414;
			
			// aapt resource value: 0x7F0700E7
			public const int txtSourceEpoch = 2131165415;
			
			// aapt resource value: 0x7F0700E8
			public const int txtSourceReferenceFrame = 2131165416;
			
			// aapt resource value: 0x7F0700E9
			public const int txtStaticEpoch = 2131165417;
			
			// aapt resource value: 0x7F0700EA
			public const int txtStationID = 2131165418;
			
			// aapt resource value: 0x7F0700EB
			public const int txtSubscription = 2131165419;
			
			// aapt resource value: 0x7F0700EC
			public const int txtSubscriptionType = 2131165420;
			
			// aapt resource value: 0x7F0700ED
			public const int txtSummary = 2131165421;
			
			// aapt resource value: 0x7F0700EE
			public const int txtSurvey = 2131165422;
			
			// aapt resource value: 0x7F0700EF
			public const int txtSurveyStatus = 2131165423;
			
			// aapt resource value: 0x7F0700F0
			public const int txtSurveyType = 2131165424;
			
			// aapt resource value: 0x7F0700F1
			public const int txtTargetReferenceFrame = 2131165425;
			
			// aapt resource value: 0x7F0700F2
			public const int txtTargetReferenceFrameId = 2131165426;
			
			// aapt resource value: 0x7F0700F3
			public const int txtTpsdkVersion = 2131165427;
			
			// aapt resource value: 0x7F0700F4
			public const int txtTransformation = 2131165428;
			
			// aapt resource value: 0x7F0700F5
			public const int txtUTCTime = 2131165429;
			
			// aapt resource value: 0x7F0700F6
			public const int txtVPrecision = 2131165430;
			
			// aapt resource value: 0x7F0700F7
			public const int txtYaw = 2131165431;
			
			// aapt resource value: 0x7F0700F8
			public const int txtYawPrecision = 2131165432;
			
			// aapt resource value: 0x7F0700F9
			public const int view_tree_lifecycle_owner = 2131165433;
			
			// aapt resource value: 0x7F0700FA
			public const int view_tree_on_back_pressed_dispatcher_owner = 2131165434;
			
			// aapt resource value: 0x7F0700FB
			public const int view_tree_saved_state_registry_owner = 2131165435;
			
			// aapt resource value: 0x7F0700FC
			public const int view_tree_view_model_store_owner = 2131165436;
			
			// aapt resource value: 0x7F0700FD
			public const int visible_removing_fragment_view_tag = 2131165437;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public const int status_bar_notification_info_maxnum = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public const int browser_actions_context_menu_page = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int browser_actions_context_menu_row = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int BthSelect = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int Configuration = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int custom_dialog = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int ime_base_split_test_activity = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int ime_secondary_split_test_activity = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Main = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int notification_action = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int notification_action_tombstone = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int notification_template_custom_big = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int notification_template_icon_group = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int notification_template_part_chronometer = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int notification_template_part_time = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int Toolbar = 2131296270;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TopConfigMenu = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TopMainMenu = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0061
			public const int androidx_startup = 2131427425;
			
			// aapt resource value: 0x7F0B0000
			public const int Antenna = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int ApplicationName = 2131427329;
			
			// aapt resource value: 0x7F0B0062
			public const int app_name = 2131427426;
			
			// aapt resource value: 0x7F0B0002
			public const int BEIDOU = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int ButtonBtPaired = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int ButtonBtselectScan = 2131427332;
			
			// aapt resource value: 0x7F0B0063
			public const int call_notification_answer_action = 2131427427;
			
			// aapt resource value: 0x7F0B0064
			public const int call_notification_answer_video_action = 2131427428;
			
			// aapt resource value: 0x7F0B0065
			public const int call_notification_decline_action = 2131427429;
			
			// aapt resource value: 0x7F0B0066
			public const int call_notification_hang_up_action = 2131427430;
			
			// aapt resource value: 0x7F0B0067
			public const int call_notification_incoming_text = 2131427431;
			
			// aapt resource value: 0x7F0B0068
			public const int call_notification_ongoing_text = 2131427432;
			
			// aapt resource value: 0x7F0B0069
			public const int call_notification_screening_text = 2131427433;
			
			// aapt resource value: 0x7F0B0005
			public const int ChangeCorrectionSourceSettings = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int CheckOnDemand = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int ChooseFile = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int ClearMarking = 2131427336;
			
			// aapt resource value: 0x7F0B006A
			public const int com_trimble_empower_modulemanager_app_name = 2131427434;
			
			// aapt resource value: 0x7F0B0009
			public const int Connect = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int ConnectionType = 2131427338;
			
			// aapt resource value: 0x7F0B006B
			public const int copy_toast_msg = 2131427435;
			
			// aapt resource value: 0x7F0B000B
			public const int CorrectionAge = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int CorrectionSource = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int Degree = 2131427341;
			
			// aapt resource value: 0x7F0B000E
			public const int DeviceAddress = 2131427342;
			
			// aapt resource value: 0x7F0B000F
			public const int DeviceConfig = 2131427343;
			
			// aapt resource value: 0x7F0B0010
			public const int DeviceSerialNumber = 2131427344;
			
			// aapt resource value: 0x7F0B0011
			public const int DeviceType = 2131427345;
			
			// aapt resource value: 0x7F0B0012
			public const int Disconnect = 2131427346;
			
			// aapt resource value: 0x7F0B0013
			public const int DriverType = 2131427347;
			
			// aapt resource value: 0x7F0B0014
			public const int Elevation = 2131427348;
			
			// aapt resource value: 0x7F0B0015
			public const int Empty = 2131427349;
			
			// aapt resource value: 0x7F0B0016
			public const int EnableLogs = 2131427350;
			
			// aapt resource value: 0x7F0B0017
			public const int EndSurvey = 2131427351;
			
			// aapt resource value: 0x7F0B0018
			public const int ExportLogs = 2131427352;
			
			// aapt resource value: 0x7F0B0019
			public const int ExternalReceiverBatteryLevel = 2131427353;
			
			// aapt resource value: 0x7F0B006C
			public const int fallback_menu_item_copy_link = 2131427436;
			
			// aapt resource value: 0x7F0B006D
			public const int fallback_menu_item_open_in_browser = 2131427437;
			
			// aapt resource value: 0x7F0B006E
			public const int fallback_menu_item_share_link = 2131427438;
			
			// aapt resource value: 0x7F0B001A
			public const int FilePath = 2131427354;
			
			// aapt resource value: 0x7F0B001B
			public const int GALILEO = 2131427355;
			
			// aapt resource value: 0x7F0B001F
			public const int Geoid = 2131427359;
			
			// aapt resource value: 0x7F0B0020
			public const int GeoidModel = 2131427360;
			
			// aapt resource value: 0x7F0B0021
			public const int GetNtripSourceList = 2131427361;
			
			// aapt resource value: 0x7F0B001C
			public const int GLONASS = 2131427356;
			
			// aapt resource value: 0x7F0B0022
			public const int GoStatic = 2131427362;
			
			// aapt resource value: 0x7F0B001D
			public const int GPS = 2131427357;
			
			// aapt resource value: 0x7F0B001E
			public const int GPSTime = 2131427358;
			
			// aapt resource value: 0x7F0B0023
			public const int GroundPositionType = 2131427363;
			
			// aapt resource value: 0x7F0B0025
			public const int Height = 2131427365;
			
			// aapt resource value: 0x7F0B0026
			public const int Hello = 2131427366;
			
			// aapt resource value: 0x7F0B006F
			public const int hello = 2131427439;
			
			// aapt resource value: 0x7F0B0024
			public const int HPrecision = 2131427364;
			
			// aapt resource value: 0x7F0B0027
			public const int IMUState = 2131427367;
			
			// aapt resource value: 0x7F0B0029
			public const int Install = 2131427369;
			
			// aapt resource value: 0x7F0B002A
			public const int InstallRTXSubscription = 2131427370;
			
			// aapt resource value: 0x7F0B0028
			public const int IRNSS = 2131427368;
			
			// aapt resource value: 0x7F0B002B
			public const int IsTransformed = 2131427371;
			
			// aapt resource value: 0x7F0B002C
			public const int Latitude = 2131427372;
			
			// aapt resource value: 0x7F0B002D
			public const int LoadSubscription = 2131427373;
			
			// aapt resource value: 0x7F0B002E
			public const int Longitude = 2131427374;
			
			// aapt resource value: 0x7F0B002F
			public const int MailLog = 2131427375;
			
			// aapt resource value: 0x7F0B0030
			public const int MarkPoints = 2131427376;
			
			// aapt resource value: 0x7F0B0031
			public const int NoOfSatellites = 2131427377;
			
			// aapt resource value: 0x7F0B0032
			public const int Ntrip = 2131427378;
			
			// aapt resource value: 0x7F0B0033
			public const int NtripServer = 2131427379;
			
			// aapt resource value: 0x7F0B0034
			public const int NtripSource = 2131427380;
			
			// aapt resource value: 0x7F0B0035
			public const int OpenFacadeLog = 2131427381;
			
			// aapt resource value: 0x7F0B0036
			public const int OutputEpoch = 2131427382;
			
			// aapt resource value: 0x7F0B0037
			public const int OutputReferenceFrame = 2131427383;
			
			// aapt resource value: 0x7F0B0038
			public const int Password = 2131427384;
			
			// aapt resource value: 0x7F0B0039
			public const int Pitch = 2131427385;
			
			// aapt resource value: 0x7F0B003A
			public const int PitchPrecision = 2131427386;
			
			// aapt resource value: 0x7F0B003B
			public const int Port = 2131427387;
			
			// aapt resource value: 0x7F0B003C
			public const int Position = 2131427388;
			
			// aapt resource value: 0x7F0B003D
			public const int QZSS = 2131427389;
			
			// aapt resource value: 0x7F0B003E
			public const int ReceivedCorrectionData = 2131427390;
			
			// aapt resource value: 0x7F0B003F
			public const int ReducedAntennaHght = 2131427391;
			
			// aapt resource value: 0x7F0B0040
			public const int Roll = 2131427392;
			
			// aapt resource value: 0x7F0B0041
			public const int RollPrecision = 2131427393;
			
			// aapt resource value: 0x7F0B0042
			public const int RtkConnectionStatus = 2131427394;
			
			// aapt resource value: 0x7F0B0043
			public const int RunGetNtripSourceList = 2131427395;
			
			// aapt resource value: 0x7F0B0045
			public const int SatelliteDefSummary = 2131427397;
			
			// aapt resource value: 0x7F0B0046
			public const int SatelliteSummary = 2131427398;
			
			// aapt resource value: 0x7F0B0047
			public const int SatelliteType = 2131427399;
			
			// aapt resource value: 0x7F0B0044
			public const int SBAS = 2131427396;
			
			// aapt resource value: 0x7F0B0048
			public const int Search = 2131427400;
			
			// aapt resource value: 0x7F0B0049
			public const int Sensor = 2131427401;
			
			// aapt resource value: 0x7F0B004A
			public const int SigmaOrientation = 2131427402;
			
			// aapt resource value: 0x7F0B004B
			public const int SigmaSemiMajorAxis = 2131427403;
			
			// aapt resource value: 0x7F0B004C
			public const int SigmaSemiMinorAxis = 2131427404;
			
			// aapt resource value: 0x7F0B004D
			public const int SolutionType = 2131427405;
			
			// aapt resource value: 0x7F0B004E
			public const int SourceEpoch = 2131427406;
			
			// aapt resource value: 0x7F0B004F
			public const int SourceReferenceFrame = 2131427407;
			
			// aapt resource value: 0x7F0B0050
			public const int StartSurvey = 2131427408;
			
			// aapt resource value: 0x7F0B0051
			public const int StaticEpoch = 2131427409;
			
			// aapt resource value: 0x7F0B0052
			public const int StationID = 2131427410;
			
			// aapt resource value: 0x7F0B0053
			public const int Status = 2131427411;
			
			// aapt resource value: 0x7F0B0070
			public const int status_bar_notification_info_overflow = 2131427440;
			
			// aapt resource value: 0x7F0B0054
			public const int Subscription = 2131427412;
			
			// aapt resource value: 0x7F0B0055
			public const int SubscriptionType = 2131427413;
			
			// aapt resource value: 0x7F0B0056
			public const int SummaryTitle = 2131427414;
			
			// aapt resource value: 0x7F0B0057
			public const int Survey = 2131427415;
			
			// aapt resource value: 0x7F0B0058
			public const int SurveyType = 2131427416;
			
			// aapt resource value: 0x7F0B0059
			public const int TargetFrameID = 2131427417;
			
			// aapt resource value: 0x7F0B005A
			public const int TargetFrameType = 2131427418;
			
			// aapt resource value: 0x7F0B005B
			public const int Transformation = 2131427419;
			
			// aapt resource value: 0x7F0B005D
			public const int UserName = 2131427421;
			
			// aapt resource value: 0x7F0B005C
			public const int UTCTime = 2131427420;
			
			// aapt resource value: 0x7F0B005E
			public const int VPrecision = 2131427422;
			
			// aapt resource value: 0x7F0B005F
			public const int Yaw = 2131427423;
			
			// aapt resource value: 0x7F0B0060
			public const int YawPrecision = 2131427424;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int AppTheme = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int TextAppearance_Compat_Notification = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int TextAppearance_Compat_Notification_Info = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification_Line2 = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Time = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int TextAppearance_Compat_Notification_Title = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int Widget_Compat_NotificationActionContainer = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int Widget_Compat_NotificationActionText = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int Widget_Support_CoordinatorLayout = 2131492872;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F030000,0x7F030001 }
			public static int[] ActivityFilter = new int[] {
					2130903040,
					2130903041};
			
			// aapt resource value: 0
			public const int ActivityFilter_activityAction = 0;
			
			// aapt resource value: 1
			public const int ActivityFilter_activityName = 1;
			
			// aapt resource value: { 0x7F030003,0x7F030030 }
			public static int[] ActivityRule = new int[] {
					2130903043,
					2130903088};
			
			// aapt resource value: 0
			public const int ActivityRule_alwaysExpand = 0;
			
			// aapt resource value: 1
			public const int ActivityRule_tag = 1;
			
			// aapt resource value: { 0x101011C,0x1010194,0x1010195,0x1010196,0x101030C,0x101030D }
			public static int[] AnimatedStateListDrawableCompat = new int[] {
					16843036,
					16843156,
					16843157,
					16843158,
					16843532,
					16843533};
			
			// aapt resource value: 3
			public const int AnimatedStateListDrawableCompat_android_constantSize = 3;
			
			// aapt resource value: 0
			public const int AnimatedStateListDrawableCompat_android_dither = 0;
			
			// aapt resource value: 4
			public const int AnimatedStateListDrawableCompat_android_enterFadeDuration = 4;
			
			// aapt resource value: 5
			public const int AnimatedStateListDrawableCompat_android_exitFadeDuration = 5;
			
			// aapt resource value: 2
			public const int AnimatedStateListDrawableCompat_android_variablePadding = 2;
			
			// aapt resource value: 1
			public const int AnimatedStateListDrawableCompat_android_visible = 1;
			
			// aapt resource value: { 0x10100D0,0x1010199 }
			public static int[] AnimatedStateListDrawableItem = new int[] {
					16842960,
					16843161};
			
			// aapt resource value: 1
			public const int AnimatedStateListDrawableItem_android_drawable = 1;
			
			// aapt resource value: 0
			public const int AnimatedStateListDrawableItem_android_id = 0;
			
			// aapt resource value: { 0x1010199,0x1010449,0x101044A,0x101044B }
			public static int[] AnimatedStateListDrawableTransition = new int[] {
					16843161,
					16843849,
					16843850,
					16843851};
			
			// aapt resource value: 0
			public const int AnimatedStateListDrawableTransition_android_drawable = 0;
			
			// aapt resource value: 2
			public const int AnimatedStateListDrawableTransition_android_fromId = 2;
			
			// aapt resource value: 3
			public const int AnimatedStateListDrawableTransition_android_reversible = 3;
			
			// aapt resource value: 1
			public const int AnimatedStateListDrawableTransition_android_toId = 1;
			
			// aapt resource value: { 0x7F030022,0x7F030025 }
			public static int[] Capability = new int[] {
					2130903074,
					2130903077};
			
			// aapt resource value: 0
			public const int Capability_queryPatterns = 0;
			
			// aapt resource value: 1
			public const int Capability_shortcutMatchRequired = 1;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x1010647,0x7F030002,0x7F030018 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					16844359,
					2130903042,
					2130903064};
			
			// aapt resource value: 3
			public const int ColorStateListItem_alpha = 3;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: 2
			public const int ColorStateListItem_android_lStar = 2;
			
			// aapt resource value: 4
			public const int ColorStateListItem_lStar = 4;
			
			// aapt resource value: { 0x7F030017,0x7F03002D }
			public static int[] CoordinatorLayout = new int[] {
					2130903063,
					2130903085};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F030019,0x7F03001A,0x7F03001B,0x7F03001C,0x7F03001D,0x7F03001E }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130903065,
					2130903066,
					2130903067,
					2130903068,
					2130903069,
					2130903070};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F030008 }
			public static int[] DrawerLayout = new int[] {
					2130903048};
			
			// aapt resource value: 0
			public const int DrawerLayout_elevation = 0;
			
			// aapt resource value: { 0x7F03000D,0x7F03000E,0x7F03000F,0x7F030010,0x7F030011,0x7F030012,0x7F030013 }
			public static int[] FontFamily = new int[] {
					2130903053,
					2130903054,
					2130903055,
					2130903056,
					2130903057,
					2130903058,
					2130903059};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F03000C,0x7F030014,0x7F030015,0x7F030016,0x7F030031 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130903052,
					2130903060,
					2130903061,
					2130903062,
					2130903089};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: 6
			public const int FontFamily_fontProviderSystemFontFamily = 6;
			
			// aapt resource value: { 0x1010003,0x10100D0,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842755,
					16842960,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public const int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public const int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 1
			public const int Fragment_android_id = 1;
			
			// aapt resource value: 0
			public const int Fragment_android_name = 0;
			
			// aapt resource value: 2
			public const int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F030021,0x7F030023,0x7F030024 }
			public static int[] SplitPairFilter = new int[] {
					2130903073,
					2130903075,
					2130903076};
			
			// aapt resource value: 0
			public const int SplitPairFilter_primaryActivityName = 0;
			
			// aapt resource value: 1
			public const int SplitPairFilter_secondaryActivityAction = 1;
			
			// aapt resource value: 2
			public const int SplitPairFilter_secondaryActivityName = 2;
			
			// aapt resource value: { 0x7F030004,0x7F030005,0x7F03000A,0x7F03000B,0x7F030026,0x7F030027,0x7F030028,0x7F030029,0x7F03002A,0x7F03002B,0x7F03002C,0x7F030030 }
			public static int[] SplitPairRule = new int[] {
					2130903044,
					2130903045,
					2130903050,
					2130903051,
					2130903078,
					2130903079,
					2130903080,
					2130903081,
					2130903082,
					2130903083,
					2130903084,
					2130903088};
			
			// aapt resource value: 0
			public const int SplitPairRule_animationBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int SplitPairRule_clearTop = 1;
			
			// aapt resource value: 2
			public const int SplitPairRule_finishPrimaryWithSecondary = 2;
			
			// aapt resource value: 3
			public const int SplitPairRule_finishSecondaryWithPrimary = 3;
			
			// aapt resource value: 4
			public const int SplitPairRule_splitLayoutDirection = 4;
			
			// aapt resource value: 5
			public const int SplitPairRule_splitMaxAspectRatioInLandscape = 5;
			
			// aapt resource value: 6
			public const int SplitPairRule_splitMaxAspectRatioInPortrait = 6;
			
			// aapt resource value: 7
			public const int SplitPairRule_splitMinHeightDp = 7;
			
			// aapt resource value: 8
			public const int SplitPairRule_splitMinSmallestWidthDp = 8;
			
			// aapt resource value: 9
			public const int SplitPairRule_splitMinWidthDp = 9;
			
			// aapt resource value: 10
			public const int SplitPairRule_splitRatio = 10;
			
			// aapt resource value: 11
			public const int SplitPairRule_tag = 11;
			
			// aapt resource value: { 0x7F030004,0x7F030009,0x7F030020,0x7F030026,0x7F030027,0x7F030028,0x7F030029,0x7F03002A,0x7F03002B,0x7F03002C,0x7F03002E,0x7F030030 }
			public static int[] SplitPlaceholderRule = new int[] {
					2130903044,
					2130903049,
					2130903072,
					2130903078,
					2130903079,
					2130903080,
					2130903081,
					2130903082,
					2130903083,
					2130903084,
					2130903086,
					2130903088};
			
			// aapt resource value: 0
			public const int SplitPlaceholderRule_animationBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int SplitPlaceholderRule_finishPrimaryWithPlaceholder = 1;
			
			// aapt resource value: 2
			public const int SplitPlaceholderRule_placeholderActivityName = 2;
			
			// aapt resource value: 3
			public const int SplitPlaceholderRule_splitLayoutDirection = 3;
			
			// aapt resource value: 4
			public const int SplitPlaceholderRule_splitMaxAspectRatioInLandscape = 4;
			
			// aapt resource value: 5
			public const int SplitPlaceholderRule_splitMaxAspectRatioInPortrait = 5;
			
			// aapt resource value: 6
			public const int SplitPlaceholderRule_splitMinHeightDp = 6;
			
			// aapt resource value: 7
			public const int SplitPlaceholderRule_splitMinSmallestWidthDp = 7;
			
			// aapt resource value: 8
			public const int SplitPlaceholderRule_splitMinWidthDp = 8;
			
			// aapt resource value: 9
			public const int SplitPlaceholderRule_splitRatio = 9;
			
			// aapt resource value: 10
			public const int SplitPlaceholderRule_stickyPlaceholder = 10;
			
			// aapt resource value: 11
			public const int SplitPlaceholderRule_tag = 11;
			
			// aapt resource value: { 0x101011C,0x1010194,0x1010195,0x1010196,0x101030C,0x101030D }
			public static int[] StateListDrawable = new int[] {
					16843036,
					16843156,
					16843157,
					16843158,
					16843532,
					16843533};
			
			// aapt resource value: { 0x1010199 }
			public static int[] StateListDrawableItem = new int[] {
					16843161};
			
			// aapt resource value: 0
			public const int StateListDrawableItem_android_drawable = 0;
			
			// aapt resource value: 3
			public const int StateListDrawable_android_constantSize = 3;
			
			// aapt resource value: 0
			public const int StateListDrawable_android_dither = 0;
			
			// aapt resource value: 4
			public const int StateListDrawable_android_enterFadeDuration = 4;
			
			// aapt resource value: 5
			public const int StateListDrawable_android_exitFadeDuration = 5;
			
			// aapt resource value: 2
			public const int StateListDrawable_android_variablePadding = 2;
			
			// aapt resource value: 1
			public const int StateListDrawable_android_visible = 1;
			
			// aapt resource value: { 0x7F03002F }
			public static int[] SwipeRefreshLayout = new int[] {
					2130903087};
			
			// aapt resource value: 0
			public const int SwipeRefreshLayout_swipeRefreshLayoutProgressSpinnerBackgroundColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0E0000
			public const int image_share_filepaths = 2131623936;
			
			// aapt resource value: 0x7F0E0001
			public const int provider_paths = 2131623937;
			
			// aapt resource value: 0x7F0E0002
			public const int xamarin_essentials_fileprovider_file_paths = 2131623938;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
